-- AgentOps Database Schema
-- Optimized for Serverless SQL (PostgreSQL)

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Projects: High-level initiatives
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused', 'cancelled')),
    priority INTEGER DEFAULT 50 CHECK (priority >= 0 AND priority <= 100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_priority ON projects(priority DESC);
CREATE INDEX IF NOT EXISTS idx_projects_created_at ON projects(created_at DESC);

-- Tasks: Specific work items
CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'blocked', 'completed', 'failed', 'cancelled')),
    assigned_to TEXT, -- agent name or 'seed', 'cos', etc.
    priority INTEGER DEFAULT 50 CHECK (priority >= 0 AND priority <= 100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    result JSONB, -- agent's output
    error TEXT, -- error message if failed
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON tasks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON tasks(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_status_priority ON tasks(status, priority DESC);

-- Task Updates: Progress tracking and communication
CREATE TABLE IF NOT EXISTS task_updates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    agent_name TEXT NOT NULL,
    update_type TEXT NOT NULL CHECK (update_type IN ('progress', 'question', 'completion', 'error', 'info')),
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_task_updates_task_id ON task_updates(task_id);
CREATE INDEX IF NOT EXISTS idx_task_updates_created_at ON task_updates(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_task_updates_type ON task_updates(update_type);

-- Agents: Registry of all agents in the system
CREATE TABLE IF NOT EXISTS agents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL CHECK (type IN ('cos', 'seed', 'specialist', 'meta')),
    status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle', 'busy', 'offline', 'error')),
    capabilities JSONB DEFAULT '[]'::jsonb, -- list of capabilities
    created_by TEXT, -- which agent created this agent
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_active_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_agents_name ON agents(name);
CREATE INDEX IF NOT EXISTS idx_agents_type ON agents(type);
CREATE INDEX IF NOT EXISTS idx_agents_status ON agents(status);
CREATE INDEX IF NOT EXISTS idx_agents_last_active ON agents(last_active_at DESC);

-- Events: System-wide event log for agent communication
CREATE TABLE IF NOT EXISTS events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type TEXT NOT NULL,
    source_agent TEXT,
    target_agent TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);
CREATE INDEX IF NOT EXISTS idx_events_source ON events(source_agent);
CREATE INDEX IF NOT EXISTS idx_events_target ON events(target_agent);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_processed ON events(processed_at) WHERE processed_at IS NULL;

-- Artifacts: Files and outputs generated by agents
CREATE TABLE IF NOT EXISTS artifacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID REFERENCES tasks(id) ON DELETE CASCADE,
    agent_name TEXT NOT NULL,
    artifact_type TEXT NOT NULL CHECK (artifact_type IN ('code', 'document', 'image', 'data', 'log', 'other')),
    name TEXT NOT NULL,
    s3_key TEXT NOT NULL, -- Object Storage key
    size_bytes BIGINT,
    mime_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_artifacts_task_id ON artifacts(task_id);
CREATE INDEX IF NOT EXISTS idx_artifacts_agent_name ON artifacts(agent_name);
CREATE INDEX IF NOT EXISTS idx_artifacts_type ON artifacts(artifact_type);
CREATE INDEX IF NOT EXISTS idx_artifacts_created_at ON artifacts(created_at DESC);

-- Tools: Registry of tools created by agents
CREATE TABLE IF NOT EXISTS tools (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_by TEXT NOT NULL, -- agent name
    tool_type TEXT NOT NULL CHECK (tool_type IN ('function', 'api', 'script', 'service')),
    implementation JSONB NOT NULL, -- code, config, or reference
    usage_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_used_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_tools_name ON tools(name);
CREATE INDEX IF NOT EXISTS idx_tools_created_by ON tools(created_by);
CREATE INDEX IF NOT EXISTS idx_tools_type ON tools(tool_type);
CREATE INDEX IF NOT EXISTS idx_tools_usage ON tools(usage_count DESC);

-- Model Usage: Track LLM model usage and costs
CREATE TABLE IF NOT EXISTS model_usage (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_name TEXT NOT NULL,
    model_name TEXT NOT NULL,
    provider TEXT NOT NULL,
    task_id UUID REFERENCES tasks(id) ON DELETE SET NULL,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    total_tokens INTEGER,
    estimated_cost_usd NUMERIC(10, 6),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_model_usage_agent ON model_usage(agent_name);
CREATE INDEX IF NOT EXISTS idx_model_usage_model ON model_usage(model_name);
CREATE INDEX IF NOT EXISTS idx_model_usage_task ON model_usage(task_id);
CREATE INDEX IF NOT EXISTS idx_model_usage_created_at ON model_usage(created_at DESC);

-- Functions for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_projects_updated_at BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON tasks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Views for common queries

-- Active tasks by priority
CREATE OR REPLACE VIEW active_tasks AS
SELECT 
    t.*,
    p.name as project_name,
    (SELECT COUNT(*) FROM task_updates WHERE task_id = t.id) as update_count
FROM tasks t
LEFT JOIN projects p ON t.project_id = p.id
WHERE t.status IN ('pending', 'in_progress', 'blocked')
ORDER BY t.priority DESC, t.created_at ASC;

-- Agent activity summary
CREATE OR REPLACE VIEW agent_activity AS
SELECT 
    a.name,
    a.type,
    a.status,
    COUNT(DISTINCT t.id) as tasks_assigned,
    COUNT(DISTINCT CASE WHEN t.status = 'completed' THEN t.id END) as tasks_completed,
    COUNT(DISTINCT CASE WHEN t.status = 'failed' THEN t.id END) as tasks_failed,
    a.last_active_at
FROM agents a
LEFT JOIN tasks t ON t.assigned_to = a.name
GROUP BY a.id, a.name, a.type, a.status, a.last_active_at;

-- Project progress summary
CREATE OR REPLACE VIEW project_progress AS
SELECT 
    p.id,
    p.name,
    p.status,
    p.priority,
    COUNT(t.id) as total_tasks,
    COUNT(CASE WHEN t.status = 'completed' THEN 1 END) as completed_tasks,
    COUNT(CASE WHEN t.status = 'in_progress' THEN 1 END) as in_progress_tasks,
    COUNT(CASE WHEN t.status = 'pending' THEN 1 END) as pending_tasks,
    COUNT(CASE WHEN t.status = 'failed' THEN 1 END) as failed_tasks,
    p.created_at,
    p.completed_at
FROM projects p
LEFT JOIN tasks t ON t.project_id = p.id
GROUP BY p.id, p.name, p.status, p.priority, p.created_at, p.completed_at;

-- Grant permissions (for serverless SQL, this is handled automatically)
-- But we'll add comments for documentation
COMMENT ON TABLE projects IS 'High-level initiatives and goals';
COMMENT ON TABLE tasks IS 'Specific work items assigned to agents';
COMMENT ON TABLE task_updates IS 'Progress updates and communication from agents';
COMMENT ON TABLE agents IS 'Registry of all agents in the system';
COMMENT ON TABLE events IS 'System-wide event log for agent communication';
COMMENT ON TABLE artifacts IS 'Files and outputs generated by agents';
COMMENT ON TABLE tools IS 'Registry of tools created by agents';
COMMENT ON TABLE model_usage IS 'Track LLM model usage and costs';

-- Insert initial seed data

-- Register core agents
INSERT INTO agents (name, type, status, capabilities, metadata) VALUES
('cos', 'cos', 'idle', '["task_management", "agent_creation", "strategic_planning", "communication"]'::jsonb, '{"description": "Chief of Staff - Strategic partner and operational executor"}'::jsonb),
('seed', 'seed', 'idle', '["task_execution", "tool_creation", "agent_creation", "general_purpose"]'::jsonb, '{"description": "Seed Agent - Founding member with self-improvement capabilities"}'::jsonb)
ON CONFLICT (name) DO NOTHING;

-- Create a welcome project
INSERT INTO projects (name, description, status, priority, metadata) VALUES
('System Initialization', 'Initial setup and validation of AgentOps system', 'active', 100, '{"auto_created": true}'::jsonb)
ON CONFLICT DO NOTHING;

-- Create a welcome task
INSERT INTO tasks (
    project_id,
    title,
    description,
    status,
    assigned_to,
    priority,
    metadata
)
SELECT 
    id,
    'Validate AgentOps System',
    'Verify all components are working: database, messaging, storage, and agent communication',
    'pending',
    'seed',
    100,
    '{"auto_created": true, "validation_task": true}'::jsonb
FROM projects 
WHERE name = 'System Initialization'
ON CONFLICT DO NOTHING;

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'AgentOps schema deployed successfully!';
    RAISE NOTICE 'Tables: projects, tasks, task_updates, agents, events, artifacts, tools, model_usage';
    RAISE NOTICE 'Views: active_tasks, agent_activity, project_progress';
    RAISE NOTICE 'Initial agents registered: cos, seed';
END $$;
